### ISSUE TITLE
Upgrade react-native 0.27.1 error

### ISSUE THREAD

**Issue by Richard-Cao** [lelandrichardson/react-native-mock#66] opened 2016-06-07 03:40 UTC
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ViewportMetrics
  Paths: /Users/caolicheng/workspace/reading/node_modules/react-native-mock/node_modules/react/lib/ViewportMetrics.js collides with /Users/caolicheng/workspace/reading/node_modules/react/lib/ViewportMetrics.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: ViewportMetrics
  Paths: /Users/caolicheng/workspace/reading/node_modules/react-native-mock/node_modules/react/lib/ViewportMetrics.js collides with /Users/caolicheng/workspace/reading/node_modules/react/lib/ViewportMetrics.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/caolicheng/workspace/reading/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at /Users/caolicheng/workspace/reading/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25

**Comment by Richard-Cao** [comment] 2016-06-07 03:41
@lelandrichardson maybe upgrade react to 15.1.0 will solve.

**Comment by RealOrangeOne** [comment] 2016-06-07 07:57
Duplicate of #64 . Try again with new version

**Closed as completed by RealOrangeOne** 2016-06-07 07:57 UTC
Labels: duplicate
