### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by devhyunjae** [lelandrichardson/react-native-mock#46] opened 2016-05-20 03:42 UTC
ChatList.js

``` javascript
import React from 'react';
import {
  View,
  Text,
} from 'react-native';

const ChatList = () => (
  <View>
    <Text>Hello world</Text>
  </View>
);

export default ChatList;
```

ChatList.test.js

``` javascript
import React from 'react';
import { View } from 'react-native';
import { shallow } from 'enzyme';
import { expect } from 'chai';
import { describe, it } from 'mocha';

import ChatList from './ChatList';

describe('ChatList', () => {
  it('should render ChatList', () => {
    const wrapper = shallow(<ChatList />);
    expect(wrapper.find(View).length).to.equal(1);
  });
});
```

test command

`mocha --require react-native-mock/mock.js --compilers js:babel-core/register --recursive src/**/*.test.js`

at this point, works fine!

in here, i am trying to use an third party libaray component.

https://github.com/GeekyAnts/NativeBase

added this line 

`import { Container, Header, Content, Footer, Title } from 'native-base';`

and run test

```
> mocha --require react-native-mock/mock.js --compilers js:babel-core/register --recursive src/**/*.test.js


node_modules/native-base/index.js:4
import Header from './Components/Widgets/Header';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:405:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/canna/my-projects/mshopbang/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

sounds like the it cannot understand the es6 syntax `import`

Is there a solution to this?

Seems like the only solution is that, change all the `import` to `require` syntax....

**Comment by RealOrangeOne** [comment] 2016-05-20 08:11
Reading the stack trace, this is coming from a module called `native-base`. You're solution would be correct. The easiest way to achieve this would be to either upgrade your version of node, as newer ones support import syntax, or you can use something like the babel-node package to do the conversion for you. But this is not a problem with `react-native-mock` in any way, shape, or form :+1

**Comment by devhyunjae** [comment] 2016-05-20 09:51
Yup, i agree this is not a react-native-mock's fault...but this will be a very common issue when trying to shallow test an 3rd party's Component that has `import` keyword :cry:

And I've tried all the approach that you have mentioned. My node version is `6.2.0`, which handles 96% compatible, but not working. Tried all kind of babel packages to but fail either.

**Comment by RealOrangeOne** [comment] 2016-05-20 11:31
Ahh, I remember the problem. By default, babel (of any kind) doesnt build any scripts that are inside the `node_modules` directory. One way you could fix this is to mock the `native-base` module, and just create some empty components, in the same way `react-native-mock` does it. Or you can use the babel `ignore` hook on require to compile just that folder (see [here](https://babeljs.io/docs/usage/require/))

**Comment by jbrodriguez** [comment] 2016-05-20 14:20
Hi @RealOrangeOne, I have a similar case in which I'm using a third party component (https://github.com/corymsmith/react-native-fabric/), while using react-native-mock.

When trying to run a test, I get

```
/Users/test/app/node_modules/react-native-fabric/Crashlytics.js:11
crash:SMXCrashlytics.crash,
TypeError: Cannot read property 'crash' of undefined
```

The code is 

```
var { NativeModules, Platform } = require('react-native');
var SMXCrashlytics = NativeModules.SMXCrashlytics;

module.exports = {

  crash: SMXCrashlytics.crash,
  throwException: SMXCrashlytics.throwException,
  .....
```

It fails because the mocked NativeModules doesn't know anything about a SMXCrashlytics, which is the expected behaviour.

Is it possible to hook into react-native-mock to include a mocked version of SMXCrashlytics (other than forking :) ) ?

**Comment by RealOrangeOne** [comment] 2016-05-20 14:45
No there is no mocking implementation with `react-native-mock` that allows you to mock `NativeModules`. The library I would recommend to achieve this is [Mockery](https://github.com/mfncooper/mockery). There's some more talk on it over at #11

**Comment by RealOrangeOne** [comment] 2016-05-25 18:45
Closing as not an issue with `react-native`. Best solution would be to run your tests using something like `babel-node` so it builds your `node_modules`, or to mock the library.

**Closed as completed by RealOrangeOne** 2016-05-25 18:45 UTC
Labels: invalid
