### ISSUE TITLE
How to access elements inside <TouchableOpacity .. /> ?

### ISSUE THREAD

**Issue by romanlv** [lelandrichardson/react-native-mock#82] opened 2016-07-18 12:56 UTC
I'm trying to test a simple component, where some areas are wrapped with <TouchableOpacity /> 

```
          <View style={styles.fieldContainer}>
            <TouchableOpacity onPress={() => {onPressHandler(...);}}>
              <IXText text={inputTime}  />
            </TouchableOpacity>
          </View>
```

I've tried different methods and rendering functions, it only can find/traverse to `TouchableOpacity` element, but not children inside it? Is it a problem of react-native-mock or enzyme?

Any ideas on how to test this component?

**Comment by RealOrangeOne** [comment] 2016-07-18 14:50
I believe this is a duplicate of #76. See there for more.

**Closed as completed by RealOrangeOne** 2016-07-18 14:50 UTC
Labels: duplicate

**Comment by romanlv** [comment] 2016-07-19 01:54
Well, somehow it works for `<View>` elements, you can wrap TextInput with `<View>` (with multiple levels) and the whole pack will be rendered by the `shallow` function. 
Can it just reuse the same logic for `TouchableOpacity` (and similar advanced containers)? For the tests it will be useful to "see through" those system elements...
